import { Component, OnInit, TemplateRef } from '@angular/core';
import { LoginService } from "src/app/services";
import { Ng4LoadingSpinnerService } from "ng4-loading-spinner";
import { BsModalService, BsModalRef } from 'ngx-bootstrap';

// import 'rxjs/Rx';
import { Http, Headers, Response } from "@angular/http";
import { saveAs } from "file-saver";
import { Router } from '@angular/router';
import { ToasterService, Toast } from 'angular2-toaster';
import { NgxXml2jsonService } from 'ngx-xml2json';
import { MerchantOnboardingService } from 'src/app/services/merchant-onboarding.service';
//declare var require;

@Component({
  selector: 'app-diy-onboarding-request',
  templateUrl: './diy-onboarding-request.component.html',
  styleUrls: ['./diy-onboarding-request.component.css']
})
export class DiyOnboardingRequestComponent implements OnInit {
  onboardedMerchantData:any;
  reqDetailArr:any = [];
  apiUrl:any = [];

  modalRef: BsModalRef;
  onoardingRequestTableData:any;
  dataSource: string[] = [];
  p: any = 1;
  role: string;
  certificate: any;
  UAT_baseURL:any = "https://apibankingonesandbox.icicibank.com"
  //showurl:Boolean;
  constructor(
    private adm: LoginService,
    private spinnerService: Ng4LoadingSpinnerService,
    private router:Router,
    private toasterService: ToasterService,
    private modalService: BsModalService,
    private merchantSrvc: MerchantOnboardingService,
  ) {
    this.request_data();
  }

  ngOnInit() {
    console.log("hi")
    
  }
  UAT_help(UAT_Help: any) {
    this.modalRef = this.modalService.show(UAT_Help, {
      backdrop: "static",
      class: "modal-lg"
    });
  }

  request_data() {
    console.log("jiii")
    
    this.spinnerService.show();
    //  this.role=localStorage.getItem('role')
    //   if(localStorage.getItem('role')=='admin'){
    //     this.showurl=true;
    //   }else{
    //   this.showurl=false;
    //   }
    this.adm.OnboardrequestsuserDiy().subscribe((data: any) => {
      var response = data._body;

      var obj = JSON.parse(response);
      this.onoardingRequestTableData=obj;
      this.onoardingRequestTableData.forEach( (myObject, index) => {
        //console.log(myObject)
        if(myObject.JiraStatus!=404){
          
          this.dataSource.push( myObject);
        
        }
      });
      this.spinnerService.hide();
    },
    err => {
      let hd=[];
     hd= 
    [{"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"mm","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.394.55","JiraId":"AG-10344","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"j","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.20.30.4","JiraId":"AG-10337","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"j","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.20.30.4","JiraId":"AG-10336","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"n","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.90.990","JiraId":"AG-10335","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"x","SpocEmail":"undefined","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.20.3333","JiraId":"AG-10334","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"x","SpocEmail":"undefined","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.20.333","JiraId":"AG-10333","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"d","SpocEmail":"undefined","RelManager":"123456789","Domain":"Composite","DomainApi":",/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/","IpList":"10.20.304","JiraId":"AG-10332","Certificate":"/u1/APIGateway/CSVData/mobCertificate/WIPRO LIMITED/File upload functionality flaw.zip","ApiName":"/api/v2/composite-payment/,/api/v3/composite-payment/,/api/v1/composite-payment/,/api/v4/composite-payment/,/api/v2/composite-status/,/api/v1/composite-status/,/api/v1/composite-validation/,","Assignee":"BAN255141"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"b","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","JiraId":"AG-10286","RefJiraId":"undefined","JiraStatus":"New","Certificate":"/u1/APIGateway/upload/AG-10286/20118239_Performance Q2_202021.zip","Remarks":"-","Assignee":"developersupport"},

    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"y","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Building Blocks","DomainApi":",431,432,433,434,435","IpList":"10.20.20.0","JiraId":"AG-9927","RefJiraId":"undefined","JiraStatus":"New","Certificate":"/u1/APIGateway/upload/AG-9927/app_uat (3).zip","Remarks":"-","ApiName":"Get Pre approved offers,Get Pre approved offers On Customer ID,Get Pre approved offers On Mobile,Pre Approved Offers,Block Pre approved offers","Assignee":"developersupport"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"y","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Building Blocks","DomainApi":",431,432,433,434,435","IpList":"10.20.20.0","JiraId":"AG-9926","RefJiraId":"undefined","JiraStatus":"New","Certificate":"/u1/APIGateway/upload/AG-9926/app_uat (3).zip","Remarks":"-","ApiName":"Get Pre approved offers,Get Pre approved offers On Customer ID,Get Pre approved offers On Mobile,Pre Approved Offers,Block Pre approved offers","Assignee":"developersupport"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"y","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Building Blocks","DomainApi":",431,432,433,434,435","IpList":"10.20.20.0","JiraId":"AG-9925","RefJiraId":"undefined","JiraStatus":"New","Certificate":"/u1/APIGateway/upload/AG-9925/app_uat (3).zip","Remarks":"-","ApiName":"Get Pre approved offers,Get Pre approved offers On Customer ID,Get Pre approved offers On Mobile,Pre Approved Offers,Block Pre approved offers","Assignee":"developersupport"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"m","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1105","IpList":"123456789","JiraId":"AG-9284","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-9284/srcUat (1).zip","Certificate":"/u1/APIGateway/upload/AG-9284/srcUat (1).zip","Remarks":"-","ApiName":"Validation Web Service","Assignee":"DEVELOPERSPORTAL"},

    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"m","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1105","IpList":"123456789","JiraId":"AG-9283","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-9283/srcUat (1).zip","Certificate":"/u1/APIGateway/upload/AG-9283/srcUat (1).zip","Remarks":"-","ApiName":"Validation Web Service","Assignee":"DEVELOPERSPORTAL"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"123","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7013632280","RelManager":"234","Domain":"Business Banking","DomainApi":"1105,1229","IpList":"10.90.90.90","JiraId":"AG-7457","RefJiraId":"undefined","JiraStatus":"Complete","Url":"/u1/APIGateway/upload/AG-7457/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-7457/formdata sequence1.png","Remarks":"-","ApiName":"Validation Web Service,E-Collection Message Holding","Assignee":"DEVELOPERSPORTAL"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"jjj","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7013632280","RelManager":"mmm","Domain":"Building Blocks","DomainApi":"801","IpList":"10.90.90.90","JiraId":"AG-7456","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7456/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-7456/formdata sequence1.png","Remarks":"-","ApiName":"Bureau Check","Assignee":"DEVELOPERSPORTAL"},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"mnnmnm","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"m","Domain":"Loans and Cards","DomainApi":"606,607","IpList":"10.203.40","JiraId":"AG-7033","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7033/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-7033/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"n","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123456","RelManager":"m","Domain":"Building Blocks","DomainApi":"801","IpList":"10.90.000","JiraId":"AG-7023","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7023/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-7023/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"jjj","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123445","RelManager":"233","Domain":"Building Blocks","DomainApi":"731","IpList":"10.90.900","JiraId":"AG-7021","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7021/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7021/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"k","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123","RelManager":"m","Domain":"Building Blocks","DomainApi":"801","IpList":"10.90.999","JiraId":"AG-7019","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7019/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7019/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"h","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123456789","RelManager":",m","Domain":"Building Blocks","DomainApi":"802","IpList":"10.90.999","JiraId":"AG-7018","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7018/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7018/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"n","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123456789","RelManager":"m","Domain":"Building Blocks","DomainApi":"431","IpList":"10.90.909","JiraId":"AG-7016","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7016/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7016/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"m","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"k","Domain":"Loans and Cards","DomainApi":"612","IpList":"10.90.90.0","JiraId":"AG-7015","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7015/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7015/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"m","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"k","Domain":"Loans and Cards","DomainApi":"612","IpList":"10.90.90.0","JiraId":"AG-7014","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7014/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7014/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"m","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"k","Domain":"Loans and Cards","DomainApi":"612","IpList":"10.90.90.0","JiraId":"AG-7013","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7013/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7013/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"m","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"k","Domain":"Loans and Cards","DomainApi":"612","IpList":"10.90.90.0","JiraId":"AG-7012","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7012/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7012/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"kk","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"j","Domain":"Building Blocks","DomainApi":"431","IpList":"10.90.90.90","JiraId":"AG-7011","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7011/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7011/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"kk","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"j","Domain":"Building Blocks","DomainApi":"431","IpList":"10.90.90.90","JiraId":"AG-7010","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7010/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7010/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"kk","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"j","Domain":"Building Blocks","DomainApi":"431","IpList":"10.90.90.90","JiraId":"AG-7009","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7009/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7009/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"kk","SpocEmail":"shikkha9@gmail.com","SpocPhone":"1234567890","RelManager":"j","Domain":"Building Blocks","DomainApi":"431","IpList":"10.90.90.90","JiraId":"AG-7008","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7008/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7008/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"cz","SpocEmail":"shikkha9@gmail.com","SpocPhone":"132323","RelManager":"jhjhj","Domain":"Building Blocks","DomainApi":"431","IpList":"10.20.309","JiraId":"AG-7007","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-7007/accIn.png","Certificate":"/u1/APIGateway/upload/AG-7007/accIn.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"vbbvb","Description":"kjjk","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123456789","RelManager":"kjkjk","Domain":"Business Banking","DomainApi":"1105","IpList":"10.90.90.90","JiraId":"AG-6348","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-6348/header (2).zip","Certificate":"/u1/APIGateway/upload/AG-6348/header (2).zip","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"kjhj","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1107","IpList":"10.50.90.0","JiraId":"AG-6274","RefJiraId":"undefined","JiraStatus":"Complete","Url":"/u1/APIGateway/upload/AG-6274/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6274/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"ADSA","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1107","IpList":"10.20.30.4","JiraId":"AG-6262","RefJiraId":"undefined","JiraStatus":"Complete","Url":"/u1/APIGateway/upload/AG-6262/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6262/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"nbb","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"undefined","Domain":"Business Banking","DomainApi":"1107","IpList":"10.90.90.9","CallbackUrl":"https://www.google.com/","JiraId":"AG-6276","RefJiraId":"undefined","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6276/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6276/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"kjhj","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1107","IpList":"10.80.80.80","CallbackUrl":"https://www.google.com/","JiraId":"AG-6275","RefJiraId":"AG-6274","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6275/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6275/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"jjj","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"(Building Blocks,Building Blocks)","DomainApi":"Bureau Check,PAN Validation","JiraId":"AG-6266","RefJiraId":"AG-6020","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6266/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6266/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"ADSA","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1107","IpList":"10.20.30.4","CallbackUrl":"https://www.google.com/","JiraId":"AG-6263","RefJiraId":"AG-6262","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6263/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6263/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"(1105)","IpList":"10.203.5","CallbackUrl":"https://www.google.com/","JiraId":"AG-6260","RefJiraId":"AG-4293","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6260/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6260/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.20.30.4","CallbackUrl":"https://www.google.com/","JiraId":"AG-6259","RefJiraId":"AG-6232","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6259/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6259/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.20.30.4","CallbackUrl":"https://www.google.com/","JiraId":"AG-6258","RefJiraId":"undefined","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6258/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6258/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.40.90.0","CallbackUrl":"https://outlook.office365.com/","JiraId":"AG-6257","RefJiraId":"undefined","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6257/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6257/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.40.90.0","CallbackUrl":"https://accounts.topcoder.com/sso-logi","JiraId":"AG-6256","RefJiraId":"undefined","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6256/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6256/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.20.30.4","CallbackUrl":"https://accounts.topcoder.com/sso-login","JiraId":"AG-6252","RefJiraId":"undefined","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6252/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6252/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.20.30.4","CallbackUrl":"https://accounts.topcoder.com/sso-login","JiraId":"AG-6251","RefJiraId":"6","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6251/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6251/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"10.20.30.40","CallbackUrl":"https://accounts.topcoder.com/sso-lo","JiraId":"AG-6250","RefJiraId":"qweq","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6250/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6250/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"kjk","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"765","IpList":"10.20.30.40","JiraId":"AG-6234","RefJiraId":"undefined","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-6234/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6234/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"Business Banking","DomainApi":"1107","IpList":"10.20.30.4","JiraId":"AG-6232","RefJiraId":"undefined","JiraStatus":"Complete","Url":"/u1/APIGateway/upload/AG-6232/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6232/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"WIPRO LIMITED","Description":"tst","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"E-Collection MIS","DomainApi":"1107","IpList":"sdf","CallbackUrl":"kjkf","JiraId":"AG-6236","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-6236/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6236/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"WIPRO LIMITED","Description":"jjj","SpocEmail":"shikkha9@gmail.com","SpocPhone":"7021142993","RelManager":"123456789","Domain":"(Building Blocks,Building Blocks)","DomainApi":"Bureau Check,PAN Validation","IpList":"10.80.80.90","JiraId":"AG-6020","RefJiraId":"undefined","JiraStatus":"Complete","Url":"/u1/APIGateway/upload/AG-6020/formdata sequence1.png","Certificate":"/u1/APIGateway/upload/AG-6020/formdata sequence1.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jajd","Description":"sadsad","SpocEmail":"asd@wrewu","SpocPhone":"123232323","RelManager":"ewew","Domain":"(Loans and Cards)","DomainApi":"(612)","JiraId":"AG-5672","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-5672/Aimcrests1.jpeg","Certificate":"/u1/APIGateway/upload/AG-5672/Aimcrests1.jpeg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"(1105)","JiraId":"AG-4762","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4762/Capture2.GIF","Certificate":"/u1/APIGateway/upload/AG-4762/Capture2.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"(1105)","IpList":"4444444","CallbackUrl":"234567","JiraId":"AG-4761","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4761/Capture2.GIF","Certificate":"/u1/APIGateway/upload/AG-4761/Capture2.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"undefined","CallbackUrl":"sdf","JiraId":"AG-4760","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4760/bkc.jpg","Certificate":"/u1/APIGateway/upload/AG-4760/bkc.jpg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"undefined","CallbackUrl":"sdf","JiraId":"AG-4759","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4759/bkc.jpg","Certificate":"/u1/APIGateway/upload/AG-4759/bkc.jpg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"PROD","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"undefined","CallbackUrl":"zcz","JiraId":"AG-4758","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4758/Capture1.GIF","Certificate":"/u1/APIGateway/upload/AG-4758/Capture1.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"wdfcwwefew","Description":"wefew","SpocEmail":"wefew@erg.ckm","SpocPhone":"1234567890","RelManager":"wefew@erg.ckm","Domain":"Validation Web Service","DomainApi":"()","CallbackUrl":"Ssd","JiraId":"AG-4756","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4756/accountopening.png","Certificate":"/u1/APIGateway/upload/AG-4756/accountopening.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"()","CallbackUrl":"kk","JiraId":"AG-4741","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4741/appathon-banner.png","Certificate":"/u1/APIGateway/upload/AG-4741/appathon-banner.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"cfgfg","Description":"fdgf","SpocEmail":"dfg@dsfods","SpocPhone":"1234567","RelManager":",,,","Domain":"Get Offer On Account","DomainApi":"(431)","JiraId":"AG-4705","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4705/Capture1.GIF","Certificate":"/u1/APIGateway/upload/AG-4705/Capture1.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"wdfcwwefew","Description":"wefew","SpocEmail":"wefew@erg.ckm","SpocPhone":"1234567890","RelManager":"wefew@erg.ckm","Domain":"Validation Web Service","DomainApi":"()","CallbackUrl":"sdfsd","JiraId":"AG-4703","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4703/app-banner.jpg","Certificate":"/u1/APIGateway/upload/AG-4703/app-banner.jpg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"wdfcwwefew","Description":"wefew","SpocEmail":"wefew@erg.ckm","SpocPhone":"1234567890","RelManager":"wefew@erg.ckm","Domain":"Validation Web Service","DomainApi":"()","CallbackUrl":"ajskja","JiraId":"AG-4698","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4698/bkc.jpg","Certificate":"/u1/APIGateway/upload/AG-4698/bkc.jpg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"Hdhhd","Description":"Hdhdg","SpocEmail":"hdhdh@hhh","SpocPhone":"12334","RelManager":"Hdhdh","Domain":"P2P - Person to Person Fund Transfer","DomainApi":"(765)","JiraId":"AG-551","RefJiraId":"Select Amount","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-551/fd1bb2dbc7f89cc8.crt","Certificate":"/u1/APIGateway/upload/AG-551/fd1bb2dbc7f89cc8.crt","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"samdnsa","Description":"asdjsa","SpocEmail":"askd@ljsa","SpocPhone":"12345678","RelManager":"sad","Domain":"Validation Web Service","DomainApi":"(1105)","JiraId":"AG-4293","RefJiraId":"Select Amount","JiraStatus":"Complete","Url":"/u1/APIGateway/upload/AG-4293/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4293/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"fh","Description":"gfh","SpocEmail":"2hm@khgfg","SpocPhone":"3456","RelManager":"mnm","Domain":"Validation Web Service","DomainApi":"(1105)","CallbackUrl":"23456","JiraId":"AG-4291","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4291/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4291/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jh","Description":"jnhj","SpocEmail":"jnj@gjj.jnj","SpocPhone":"3343","RelManager":" nnn","Domain":"CDM Validation","DomainApi":"(1122)","JiraId":"AG-4273","RefJiraId":"Select Amount","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4273/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4273/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"null","Description":"null","SpocEmail":"null","SpocPhone":"null","RelManager":"null","Domain":"Instant Fund Transfer","DomainApi":"()","JiraId":"AG-4272","JiraStatus":"404","Certificate":"","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"rew","Description":"wer","SpocEmail":"wer@jfdfs","SpocPhone":"123","RelManager":"ds","Domain":"Auto Loan Generate OTP","DomainApi":"(612)","JiraId":"AG-4254","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4254/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4254/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"Gg","Description":"Hh","SpocEmail":"g@gbnn.gnn","SpocPhone":"245","RelManager":"Hhh","Domain":"Bureau Check","DomainApi":"(801)","JiraId":"AG-4225","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4225/15937699848828836986367625758048.jpg","Certificate":"/u1/APIGateway/upload/AG-4225/15937699848828836986367625758048.jpg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"sadaf","Description":"sdfd","SpocEmail":"sdfds@dsfds","SpocPhone":"12345678","RelManager":"dsfkdsf","Domain":"Validation Web Service","DomainApi":"(1105)","JiraId":"AG-4212","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4212/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4212/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"asd","Description":"asdsa","SpocEmail":"asdsa@safkkk","SpocPhone":"12345678","RelManager":"ada","Domain":"Validation Web Service, Outward Remittance","DomainApi":"(1105,1209)","JiraId":"AG-4209","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4209/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4209/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"sads","Description":"sdfdssdfds","SpocEmail":"sdf@kdsfkds","SpocPhone":"2345678","RelManager":"sadsa","Domain":"Validation Web Service","DomainApi":"(1105)","CallbackUrl":"sad","JiraId":"AG-4208","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4208/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4208/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"qwewq","Description":"qwewq","SpocEmail":"qwe@ewknrew.fds","SpocPhone":"12345678","RelManager":"asdsad","Domain":"Outward Remittance","DomainApi":"(1209)","JiraId":"AG-4207","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4207/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4207/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"nb","Description":"mn","SpocEmail":"mnm@mbkjk","SpocPhone":"56789","RelManager":"mmn","Domain":"Get Offer On Account","DomainApi":"(431)","JiraId":"AG-4206","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4206/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4206/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"nbnn","Description":"mmm","SpocEmail":"lklkl@hghh","SpocPhone":"12356789","RelManager":",m,","Domain":"CDM Validation","DomainApi":"(1122)","JiraId":"AG-4189","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4189/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4189/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"ymlkt","Description":"hnhg","SpocEmail":"fgbf2kkdfk@kkgktr","SpocPhone":"12345678","RelManager":"kjkj","Domain":"Generate OTP, Aadhar OTP verification","DomainApi":"(731,740)","JiraId":"AG-4188","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4188/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4188/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"fgdf","Description":"dfh","SpocEmail":"gfhf@kjnkjgd","SpocPhone":"1234567","RelManager":"mnm","Domain":"Outward Remittance","DomainApi":"(1209)","JiraId":"AG-4187","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4187/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4187/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jhj","Description":"hgfhg","SpocEmail":"ygya@hghjgh","SpocPhone":"12345678","RelManager":"jnkjn","Domain":"FD Creation","DomainApi":"(702)","JiraId":"AG-4186","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4186/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4186/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"sdfdsf","Description":"sdfds","SpocEmail":"sdf@fdmgfdg","SpocPhone":"12345678","RelManager":"fgh","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"(1105,1106)","JiraId":"AG-4185","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4185/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4185/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jmkjjb","Description":"lklk","SpocEmail":"lkl@fgfc","SpocPhone":"12345678","RelManager":".ll","Domain":"Outward Remittance","DomainApi":"(1209)","JiraId":"AG-4183","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4183/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4183/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"Hhhh","Description":"Vgg","SpocEmail":"hh@hhggj","SpocPhone":"34667","RelManager":"Bhhh","DomainApi":"(1234)","JiraId":"AG-4177","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4177/1593542318354934280045854440646.jpg","Certificate":"/u1/APIGateway/upload/AG-4177/1593542318354934280045854440646.jpg","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"sadjdsad","Description":"asdkjsad","SpocEmail":"sadjsa@jdskhfd","SpocPhone":"12345678","RelManager":"asdsad","Domain":"Issuance API","DomainApi":"(1206)","JiraId":"AG-4171","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4171/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4171/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"asdsa","Description":"asd","SpocEmail":"asdlka@ijsfdds","SpocPhone":"12345678","RelManager":"sdfdsf","Domain":"Outward Remittance","DomainApi":"(1209)","JiraId":"AG-4170","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4170/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4170/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"vxc","Description":"xvc","SpocEmail":"xcv@zvxxc","SpocPhone":"0987654321","RelManager":"ZZcz","Domain":"Outward Remittance","DomainApi":"(1209)","JiraId":"AG-4148","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4148/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4148/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"retret","Description":"efdmgmd","SpocEmail":"djfgjf@jdgh","SpocPhone":"12345678","RelManager":"asdmkaf","Domain":"RD Creation","DomainApi":"(705)","JiraId":"AG-4147","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4147/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4147/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"lijewr","Description":"werewr","SpocEmail":"werewr@lksfsd","SpocPhone":"123457890","RelManager":"asdsadsd","Domain":"Validation Web Service","DomainApi":"(1105)","JiraId":"AG-4145","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4145/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4145/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"zcxzc","Description":"zxcxz","SpocEmail":"zxcz@fmgmfd.xcv","SpocPhone":"123456789","RelManager":"dfdskf@odko.dsfds","Domain":"Outward Remittance","DomainApi":"Outward Remittance(1209)","JiraId":"AG-4142","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4142/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4142/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jhj","Description":"jnjn","SpocEmail":"jjnbj@gfhgv","SpocPhone":"123456789","RelManager":"llmm@gfchg.uyiu","Domain":"Outward Remittance","DomainApi":"Outward Remittance(1209)","JiraId":"AG-4141","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4141/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4141/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"dsfdsf","Description":"dsfdsf","SpocEmail":"sdgfds@ljksd.xzc","SpocPhone":"1234567890","RelManager":"kdslkd@kms.dslkfl","Domain":"Auto Loan Generate OTP","DomainApi":"OTP Creation(612)","JiraId":"AG-4140","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4140/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4140/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jnm","Description":"jnj","SpocEmail":"nbnnbn@fcf.oko","SpocPhone":"1234567890","RelManager":"bvbbbbbbbbb@gfgmmmmmmmmm","Domain":"Outward Remittance","DomainApi":"Outward Remittance(1209)","JiraId":"AG-4139","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4139/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4139/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"dskfbdsf","Description":"sdhn","SpocEmail":"dsfds@iudsijf","SpocPhone":"123456789","RelManager":"sijdsfi@keksfds","Domain":"Outward Remittance","DomainApi":"Outward Remittance(1209)","JiraId":"AG-4138","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4138/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4138/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"ldsgd","Description":"dflkgjfd","SpocEmail":"fd@jdsj..cv","SpocPhone":"1234567890","RelManager":"kjnkjn@rdf.oii","Domain":"Outward Remittance","DomainApi":"Outward Remittance(1209)","JiraId":"AG-4137","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4137/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4137/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"sfg","Description":"dfgfd","SpocEmail":"fd@hhjsfg","SpocPhone":"12367890","RelManager":"fcf@fhthm","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","JiraId":"AG-4121","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4121/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4121/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"dshufdsf","Description":"sdijfoids","SpocEmail":"sdks@jndskf.xcdsf","SpocPhone":"1234567890","RelManager":"sdks@jndskf.xcdsf","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","CallbackUrl":"wwq","JiraId":"AG-4112","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4112/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4112/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"sadndsa","Description":"askdnsak","SpocEmail":"askdlksa@knkdsf.vdos","SpocPhone":"123456789","RelManager":"lkdsflkds@ijewd.xzv","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","JiraId":"AG-4084","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4084/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4084/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"kknk","Description":"l,mll","SpocEmail":"mm@xfc.nbb","SpocPhone":"12367890","RelManager":"nbnbn@fhfh.vbbv","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","JiraId":"AG-4077","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4077/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4077/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"vvnnn","Description":"kjjhj","SpocEmail":"mm@lkjl.cvc","SpocPhone":"123456789","RelManager":"ddxc@lklk.vcvc","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4076","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4076/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4076/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jsajd","Description":"dflkds","SpocEmail":"sdkfdlk@clkvm.cxklk","SpocPhone":"123457890","RelManager":"lldslfl@lkdslk.xcllx","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4073","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4073/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4073/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"testing","Description":"testing","SpocEmail":"testing@gsajsaj.cxcj","SpocPhone":"1234567890","RelManager":"testing@gdsfds.com","Domain":"E-Collection MIS","DomainApi":"eCollection MIS(1107)","JiraId":"AG-4072","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4072/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4072/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"zjjsad","Description":"oidfoids","SpocEmail":"sifsoij@nkenfie","SpocPhone":"1235789","RelManager":"jfdsfkj@kjkdsf.xer","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4070","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4070/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4070/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jdsds","Description":"djfdsj","SpocEmail":"kdsfsjf@ijdsf.coijv","SpocPhone":"1234567890","RelManager":"ksfdsjf@iujwoi.xcvij","Domain":"Bureau Check, Validation Web Service","DomainApi":"Bureau Check,Validation Web Service(801,1105)","JiraId":"AG-4067","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4067/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4067/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"ugjghj","Description":"hhk","SpocEmail":"iuiuhik@ygujhk.hch","SpocPhone":"1237890","RelManager":"hjkj@glchgihi.hjghhgh","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4064","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4064/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4064/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jhjhj","Description":"kjkjk","SpocEmail":"kjlkj@gkjl","SpocPhone":"1230567890","RelManager":"jhjghjgj@kk.cn","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4061","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4061/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4061/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jdsjfd","Description":"fdnf","SpocEmail":"fdk@hhd.vom","SpocPhone":"1234567890","RelManager":"fggf@fyugyu.cbm","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4059","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4059/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4059/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"dsvdf","Description":"dfvfdv","SpocEmail":"fd@hfdh.cl","SpocPhone":"123467890","RelManager":"fd@hfdh.cl","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-4058","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4058/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4058/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jhj","Description":"jhj","SpocEmail":"jhhjhj@hgj.vbm","SpocPhone":"1234567890","RelManager":"hhf@ygyg.vn","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","CallbackUrl":"23456789","JiraId":"AG-4056","JiraStatus":"New","Url":"/u1/APIGateway/upload/AG-4056/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4056/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"hj","Description":"hjj","SpocEmail":"nmm@jj.cb","SpocPhone":"1234567890","RelManager":"mnmn@hg,vn","Domain":"Get Offer On Account","DomainApi":"Get Pre approved offers(431)","JiraId":"AG-4039","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4039/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4039/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"jhhj","Description":"jjj@v","SpocEmail":"jjjj@gvhg.no","SpocPhone":"0987654321","RelManager":"jghvhgv@gfcgcgf.bhb","Domain":"Get Offer On Account","DomainApi":"Get Pre approved offers(431)","JiraId":"AG-4016","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-4016/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-4016/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"t","Description":"t","SpocEmail":"t@gmail.co","SpocPhone":"1234567890","RelManager":"t@gmail.co","Domain":"Bureau Check","DomainApi":"Bureau Check(801)","JiraId":"AG-3989","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3989/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3989/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"t","Description":"t","SpocEmail":"t@gmail.com","SpocPhone":"098765432","RelManager":"t@gad.co","Domain":"Get Token UPI 1.0","DomainApi":"Get Token(125)","JiraId":"AG-3988","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3988/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3988/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"t","Description":"t","SpocEmail":"t@gm.com","SpocPhone":"8654321","RelManager":"t@gm.com","Domain":"Accounts and Deposits","DomainApi":"FD Creation(702)","JiraId":"AG-3987","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3987/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3987/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"t","Description":"t","SpocEmail":"t@gmial.co","SpocPhone":"0987654321","RelManager":"t@hdsh.vom","Domain":"FD Creation","DomainApi":"FD Creation(702)","JiraId":"AG-3986","JiraStatus":"404","Certificate":"","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"r","Description":"r","SpocEmail":"r@f.com","SpocPhone":"0987654321","RelManager":"r@f.com","Domain":"Auto Loan Generate OTP","DomainApi":"OTP Creation(612)","JiraId":"AG-3985","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3985/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3985/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"test","Description":"test","SpocEmail":"test@gmail.com","SpocPhone":"0987654321","RelManager":"test@gmail.com","Domain":"Outward Remittance","DomainApi":"Outward Remittance(1209)","JiraId":"AG-3984","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3984/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3984/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"test","Description":"test","SpocEmail":"test@gmail.com","SpocPhone":"0987654321","RelManager":"test@gksa.co","Domain":"Validate Virtual Address  UPI 2.0","DomainApi":"Validate Virtual Address(107)","JiraId":"AG-3983","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3983/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3983/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"test","Description":"test","SpocEmail":"test@gmail.com","SpocPhone":"0987654321","RelManager":"test@hmail.co","Domain":"Auto Loan Generate OTP","DomainApi":"OTP Creation(612)","JiraId":"AG-3981","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3981/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3981/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"Testing","Description":"Testing","SpocEmail":"testing@gmail.com","SpocPhone":"12357890","RelManager":"testing@gmail.com","Domain":"Registration Status","DomainApi":"Registration Status(709)","JiraId":"AG-3979","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3979/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3979/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"Testing","Description":"Testing","SpocEmail":"testing@gmail.com","SpocPhone":"123456789","RelManager":"v@gmailc.om","Domain":"Auto Loan Generate OTP","DomainApi":"OTP Creation(612)","JiraId":"AG-3978","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3978/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3978/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"Testing","Description":"Testing","SpocEmail":"testing@gmail.com","SpocPhone":"1234567890","RelManager":"testing@112345.com","Domain":"Get Token UPI 1.0","DomainApi":"Get Token(125)","JiraId":"AG-3977","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3977/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3977/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"test","Description":"test","SpocEmail":"test@kdsfkj.com","SpocPhone":"0987654321","RelManager":"test@jf.com","Domain":"Get Token UPI 1.0","DomainApi":"Get Token(125)","JiraId":"AG-3975","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3975/additional Field.GIF","Certificate":"/u1/APIGateway/upload/AG-3975/additional Field.GIF","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"testing","Description":"testing","SpocEmail":"testing@gmail.com","SpocPhone":"1234567890","RelManager":"testing@gmail.com","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-3899","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3899/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3899/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"test","Description":"test","SpocEmail":"test@gmail.com","SpocPhone":"1234567890","RelManager":"test@gmail.com","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-3895","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3895/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3895/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"test","Description":"test","SpocEmail":"test@jhf.com","SpocPhone":"1257890","RelManager":"test@jhf.com","Domain":"Validation Web Service, E-Collection MIS","DomainApi":"Validation Web Service,eCollection MIS(1105,1107)","JiraId":"AG-3891","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3891/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3891/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"kjgkjfd","Description":"fgkdg","SpocEmail":"fdglfdkg@hgehg.com","SpocPhone":"123567890","RelManager":"jjhj@bh.vom","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","JiraId":"AG-3858","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3858/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3858/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"kjgkjfd","Description":"fgkdg","SpocEmail":"fdglfdkg@hgehg.com","SpocPhone":"123567890","RelManager":"jjhj@bh.vom","Domain":"Validation Web Service, Receipting Web Service","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","JiraId":"AG-3857","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3857/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3857/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"wdfcwwefew","Description":"wefew","SpocEmail":"wefew@erg.ckm","SpocPhone":"1234567890","RelManager":"wefew@erg.ckm","Domain":"Validation Web Service","DomainApi":"Validation Web Service(1105)","JiraId":"AG-3856","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3856/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3856/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"ffd","Description":"fgff","SpocEmail":"testing@gjdjg.com","SpocPhone":"1234567890","RelManager":"testing@gjdjg.com","Domain":"Business Banking","DomainApi":"Validation Web Service,Receipting Web Service(1105,1106)","JiraId":"AG-3855","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3855/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3855/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"e54656","Description":"Description","SpocEmail":"Description@mail.id","SpocPhone":"1234567890","RelManager":"Description@mail.id","Domain":"Building Blocks","DomainApi":"Get Pre approved offers(431)","IpList":"90.90.90.90","JiraId":"AG-3825","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3825/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3825/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "},
    {"Env":"UAT","MerchantName":"e54656","Description":"jsadjsad","SpocEmail":"shikkha9@gmail.com","SpocPhone":"123567890","RelManager":"shikkha9@gmail.com","Domain":"Building Blocks","DomainApi":"Get Pre approved offers(431)","IpList":"80.90.80.90","JiraId":"AG-3824","JiraStatus":"404","Url":"/u1/APIGateway/upload/AG-3824/1sSsection.png","Certificate":"/u1/APIGateway/upload/AG-3824/1sSsection.png","Remarks":" ","ApiName":" ","Assignee":" "}]

        this.dataSource=hd;
      console.log('err', err);
     // this.router.navigate(['error']);
      this.toastrmsg('error',"Something went wrong. Please try again in some time.");
      
    },);
  }

  //supporting .sql,.cer (not supporting .png, .docx)
  downloadCertificate(url) {
    var json = {
      filePath: url
    };

    var fileName = url.substring(url.lastIndexOf("/") + 1);
    this.adm.downloadCertificate(json).subscribe((data: any) => {
      this.certificate = data._body;
      console.log(data._body);
      var blob = new Blob([this.certificate], {
        type: "text/plain"
      });
      saveAs(blob, fileName);
    },
    err => {
      console.log('err', err);
     // this.router.navigate(['error']);
      this.toastrmsg('error',"Something went wrong. Please try again in some time.");
    },);
  }
  openModal(viewDetail: TemplateRef<any>,id) {
    console.log(id);
    this.onboardedMerchantData = this.dataSource[id];
    console.log(this.onboardedMerchantData);
    this.apiUrl = this.onboardedMerchantData.ApiName.split(','); 
    this.modalRef= this.modalService.show(viewDetail, { backdrop: "static",class: 'modal-lg'});    
  }


  downloadDocument(jiraID,type,url) {
    var json = {
      jiraid: jiraID,
      type:type
    };

    var fileName = url.substring(url.lastIndexOf("/") + 1);

    this.adm.customDownload(json).subscribe((data: any) => {
      this.certificate = data._body;
      console.log(data._body);
      var blob = new Blob([this.certificate], {
        type: "text/plain"
      });
      saveAs(blob, fileName);
    },
    err => {
      console.log('err', err);
     // this.router.navigate(['error']);
      this.toastrmsg('error',"Something went wrong. Please try again in some time.");
    },);
  }
  downloadfile(path,filename){
    this.merchantSrvc.downloadFromURL(path).subscribe((data: any) => {
      console.log(data);
      let certificate = data._body;
      console.log(data._body);
      var blob = new Blob([certificate], {
        type: "text/plain"
      });
      saveAs(blob, filename+"_ICICI_PUBLIC_CERT");
    },
    err => {
      console.log('err', err);
     
    });
  }

  toastrmsg(type ,title){
    var toast: Toast = {
      type: type,
      title:"",
      body:title,
      showCloseButton: true 
    }; 
    this.toasterService.pop(toast);
  }
  closeMe(){
    // this.getDiyOnboardingReq();
    this.modalRef.hide();
  }
  
}
